#!/usr/bin/env python
"""Generate the two h3ir arms of the acceptance comparison.

Inputs are fixed to match the arms already rendered, so the only thing that varies between
arms is the prompt text. Nothing here is parameterised on purpose: a knob is a chance for this
arm to differ from the others in a way nobody notices.
"""
from __future__ import annotations

import sys
import os
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from h3ir.analyse import sha256_file
from h3ir.compile import compile_brief
from h3ir.models import AssetKind, AssetRef, Brief, Role
from h3ir.plan import ProfileOptions
from h3ir.tokens import count as tok, word_count
from h3ir.validate import Report

REQUEST = ("the man walks forward down the stone corridor toward the camera, torchlight "
           "flickering across the walls. Anime style, cinematic, steady slow forward camera "
           "push. No dialogue. No background music.")

# Point these at your own reference plates. A character turnaround sheet and an empty
# location plate is the pair these scripts were written against.
IMAGE_DIR = Path(os.environ.get("H3IR_REF_IMAGE_DIR", "."))
# The character sheet is passed WHOLE and uncropped, to get the empirical answer to whether H3
# reads a turnaround as a turnaround. Do not substitute a crop from an earlier render: doing
# that once preserved a drift from the render instead of the character it was meant to test.
CHARACTER = IMAGE_DIR / os.environ.get("H3IR_REF_CHARACTER",
                                       "character_turnaround.png")
CORRIDOR = IMAGE_DIR / os.environ.get("H3IR_REF_SCENE", "bare_corridor.png")

SECONDS = 8.0                 # 192 frames exactly — the only integer second on the 17k+5 grid
# Pinned to the geometry the already-rendered arms used. It is a flag because the geometry
# question is open: whatever the graph owner lands on, all four arms must use the SAME value or
# the comparison stops meaning anything.
#   python make_acceptance_arm.py --canvas 1920x1088
# Canvas is deliberately NOT pinned. It never appears in the IR text -- only the frame count does,
# through S.SS and the cut times -- so the graph can carry whatever geometry the plumbing settles
# on without changing a byte of these arms.
CANVAS = None
SEED = 7
OUT = Path("acceptance")


# A transformation request, kept available but NOT generated by default. Under the settled rule a
# bare adjective changes nothing, so an arm with "Anime style" removed is byte-identical in intent
# to the one that has it -- there is nothing left to compare. The contrast that now means
# something is an explicit transformation, which routes the plate to attribute_transfer.
#   python make_acceptance_arm.py --transform
REQUEST_TRANSFORM = ("reimagine the man as anime as he walks forward down the stone corridor "
                     "toward the camera, torchlight flickering across the walls. Cinematic, "
                     "steady slow forward camera push. No dialogue. No background music.")


# The plain version of the same request, with the prohibitions and the camera instruction removed.
# It exists so the creativity dial can be SEEN: the canonical request forbids dialogue and music, and
# a prohibition outranks every setting, so restrained and bold are identical against it by design.
#   python make_acceptance_arm.py --creativity bold --plain
REQUEST_PLAIN = ("the man walks forward down the stone corridor toward the camera, torchlight "
                 "flickering across the walls. Cinematic.")


def brief(intent: str | None = None, creativity: str = "balanced",
          silent: bool = True) -> Brief:
    return Brief(
        creativity=creativity,
        intent=intent or REQUEST,
        seconds=SECONDS,
        aspect="16:9",
        canvas=CANVAS,
        # Order is load-bearing: it becomes <Picture 1> then <Picture 2>.
        assets=[
            AssetRef(kind=AssetKind.IMAGE, role=Role.SUBJECT, sha256=sha256_file(CHARACTER),
                     path=str(CHARACTER), note="the man (character turnaround sheet)",
                     px=(1448, 1086)),
            AssetRef(kind=AssetKind.IMAGE, role=Role.ENVIRONMENT, sha256=sha256_file(CORRIDOR),
                     path=str(CORRIDOR), note="the stone corridor (environment reference)",
                     px=(403, 552)),
        ],
        # The canonical request says no background music. That is non-diegetic score only;
        # torchlight and footsteps still belong in the soundscape. The plain arm clears it, because
        # a prohibition outranks every creativity setting -- leaving it on would make restrained and
        # bold identical and the dial invisible, which is the opposite of what that arm is for.
        silent=silent,
        # No dialogue: the list stays empty, so no (Sx) and no <d> can be produced at all.
        dialogue=[],
    )


def _ask_sheet(name: str, b: Brief, doc) -> str:
    """The request, the settings and the result in one readable file."""
    main_field = ("detailed_description" if "detailed_description" in doc.sections
                  else "integrated_multimodal_description")
    refs = "\n".join(f"- `{m.label}` — {m.role.value} — {Path(a.path).name}"
                      for m, a in zip(doc.plan.manifest, b.assets)) or "- none"
    return (
        f"# {name}\n\n"
        f"## What was asked\n\n> {b.intent}\n\n"
        f"{refs}\n\n"
        f"| setting | value |\n|---|---|\n"
        f"| creativity | **{b.creativity}** |\n"
        f"| scope decided | {doc.provenance.get('creativity')} |\n"
        f"| duration | {doc.plan.target.frames} frames = "
        f"{doc.plan.target.effective_seconds:.3f}s |\n"
        f"| seed | {doc.provenance.get('seed')} |\n"
        f"| mode | {doc.mode.value} ({doc.plan.mode_decision.rule_fired}) |\n"
        f"| source | {doc.provenance.get('source')}"
        + (f" — fallback: {doc.provenance.get('fallback_reason')}"
           if doc.provenance.get("fallback_reason") else "") + " |\n"
        f"| shots | {len(doc.plan.shots)} |\n"
        f"| cuts | {[s.cut_timestamp for s in doc.plan.shots if s.cut_timestamp] or 'none'} |\n"
        f"| words in {main_field} | {word_count(doc.sections[main_field])} |\n"
        f"| speech | {'yes' if '<d>' in doc.prompt else 'none'} |\n"
        f"| score | {doc.sections.get('non_diegetic_music', '').strip()!r} |\n\n"
        f"## What came back\n\n```text\n{doc.prompt}```\n"
    )


def main(argv: list[str] | None = None) -> int:
    import argparse

    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--canvas", default=None,
                    help="WxH, both multiples of 32. Optional: canvas never reaches the IR text, "
                         "so leaving it unset lets the graph carry the geometry.")
    ap.add_argument("--seconds", type=float, default=SECONDS)
    ap.add_argument("--seed", type=int, default=SEED)
    ap.add_argument("--out", default=str(OUT))
    ap.add_argument("--transform", action="store_true",
                    help="also emit an explicit-transformation arm (attribute_transfer)")
    ap.add_argument("--creativity", choices=["restrained", "balanced", "bold", "extreme"], default="balanced",
                    help="how much the writer may add beyond the request")
    ap.add_argument("--plain", action="store_true",
                    help="use the request with no prohibitions and no camera instruction, so the "
                         "creativity setting is the only thing acting on the output")
    ap.add_argument("--label", default=None, help="suffix for the arm filenames")
    args = ap.parse_args(argv)
    if args.canvas:
        w, h = (int(x) for x in args.canvas.lower().split("x"))
        globals()["CANVAS"] = (w, h)
    else:
        w = h = 0
    globals()["SECONDS"] = args.seconds
    globals()["SEED"] = args.seed
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    globals()["OUT"] = out_dir
    print(f"canvas {'%dx%d' % (w, h) if w else 'not pinned (graph carries it)'}, "
          f"{args.seconds}s, seed {args.seed}")
    opts = ProfileOptions(name="h3ir/2026-08-a")
    base = REQUEST_PLAIN if args.plain else None
    suffix = args.label or (f"_{args.creativity}" if args.creativity != "balanced" else "")
    arms = [
        (f"arm0_h3ir_draft_no_llm{suffix}", False, base),
        (f"arm4_h3ir_compiled{suffix}", True, base),
    ]
    if args.transform:
        arms.append((f"arm4t_h3ir_compiled_transformed{suffix}", True, REQUEST_TRANSFORM))
    for name, llm, intent in arms:
        b = brief(intent, creativity=args.creativity, silent=not args.plain)
        doc = compile_brief(b, opts=opts, seed=SEED, llm=llm)
        path = out_dir / f"{name}.txt"
        path.write_text(doc.prompt, encoding="utf-8")
        # The brief alone is unjudgeable. Nobody can tell whether an output matched a plain request
        # or overshot it while looking only at the output, so the ask ships beside the result.
        (out_dir / f"{name}.ask.md").write_text(_ask_sheet(name, b, doc), encoding="utf-8")

        main_field = ("detailed_description" if "detailed_description" in doc.sections
                      else "integrated_multimodal_description")
        print(f"\n{'=' * 78}\n{name}\n{'=' * 78}")
        print(f"  file        {path}")
        print(f"  mode        {doc.mode.value}   ({doc.plan.mode_decision.rule_fired}, "
              f"conf {doc.plan.mode_decision.confidence:.2f})")
        print(f"  source      {doc.provenance['source']}"
              + (f"   fallback: {doc.provenance['fallback_reason']}"
                 if doc.provenance.get("fallback_reason") else ""))
        print(f"  target      {doc.plan.target.frames} frames = "
              f"{doc.plan.target.effective_seconds:.3f}s   canvas "
              f"{doc.plan.target.canvas[0]}x{doc.plan.target.canvas[1]}")
        print(f"  shots       {len(doc.plan.shots)}  cuts at "
              f"{[s.cut_timestamp for s in doc.plan.shots if s.cut_timestamp]}")
        print(f"  camera      {[(s.camera.type, s.camera.amplitude, s.camera.speed) for s in doc.plan.shots if s.camera]}")
        print(f"  size        {len(doc.prompt)} chars, {tok(doc.prompt)} tokens, "
              f"{word_count(doc.sections[main_field])} words in {main_field}")
        print(f"  music       {doc.sections.get('non_diegetic_music', '').strip()!r}")
        print(f"  style       {doc.plan.style_phrase!r}")
        print(f"  wiring      " + ", ".join(
            f"{m.label}<-{Path(next(a.path for a in brief().assets if a.sha256 == m.sha256)).name}"
            for m in doc.plan.manifest))
        print(Report(name, doc.findings).text(show_info=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
